# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Dragon's Lair
tagline:             'My Personal D&D Lair'
description:         'A site for D&D enthusiasts, by a D&D enthusiast'
url:                 https://thevinter.github.io/dragonsden/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nik Vinter
  url:               github.com/thevinter
  email:             nikita.brancatisano@gmail.com

# Custom vars
version:             1.3.0

